baseURL: 'https://www.colinspear.com'
# languageCode: en-us
title: Colin Spear
theme: PaperMod
paginate: 10
# copyright: Colin Spear

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-BFJ2WK0V8F

minify:
    disableXML: true
    minifyOutput: true

ignoreFiles:
  - learning
  - google-docs
  - scrap
  - todo
  - notes
  - goals-habits

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    title: Colin Spear
    description: "A digital home for all I'd like to share"
    keywords: [Blog, Portfolio, PaperMod]
    author: Me
    # author: ["Me", "You"] # multiple authors
    # images: ["<link or path of image for opengraph, twitter-cards>"]
    DateFormat: "January 2, 2006"
    defaultTheme: auto # dark, light
    disableThemeToggle: false

    ShowReadingTime: true
    ShowShareButtons: false
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: false
    disableSpecial1stPost: True
    disableScrollToTop: false
    comments: false
    hidemeta: false
    hideSummary: false
    showtoc: false
    tocopen: false

    # assets:
        # disableHLJS: true # to disable highlight.js
        # disableFingerprinting: true
        # favicon: "/favicon.ico"
        # favicon16x16: "/favicon.ico"
        # favicon32x32: "/favicon.ico"
        # apple_touch_icon: "<link / abs url>"
        # safari_pinned_tab: "<link / abs url>"

    label:
        # text: "Home"
        icon: /logo-fill.png
        iconHeight: 35

    # profile-mode
    # profileMode:
    #     enabled: false # needs to be explicitly set
    #     title: ExampleSite
    #     subtitle: "This is subtitle"
    #     imageUrl: "<img location>"
    #     imageWidth: 120
    #     imageHeight: 120
    #     imageTitle: my image
    #     buttons:
    #         - name: Posts
    #           url: posts
    #         - name: Tags
    #           url: tags

    # home-info mode
    homeInfoParams:
        Title: "Hi there" # \U0001F44B"
        Content: Welcome to my garden

    socialIcons:
        - name: twitter
          url: "https://twitter.com/colinspear"
        # - name: stackoverflow
          # url: "https://stackoverflow.com"
        - name: github
          url: "https://github.com/colinspear"
        - name: email
          url: "colinspear@gmail.com"

    analytics:
        google:
            SiteVerificationTag: "XYZabc"
        bing:
            SiteVerificationTag: "XYZabc"
        yandex:
            SiteVerificationTag: "XYZabc"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # editPost:
    #     URL: "https://github.com/colinspear/colinspear-site/content"
    #     Text: "Suggest Changes" # edit text
    #     appendFilePath: true # to append file path to Edit link

    # for search

    outputs:
    home:
        - HTML
        - RSS
        - JSON # is necessary

    # https://fusejs.io/api/options.html
    fuseOpts:
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]

        
menu:
    main:
        - identifier: posts
          name: Technical
          url: /technical-posts/
          weight: 2
        - identifier: links
          name: Links
          url: /links/
          weight: 1
        - identifier: notes
          name: Notes
          url: /thoughts-posts/
          weight: 2
        - identifier: books
          name: Books
          url: /books/
          weight: 3
        - identifier: tags
          name: Tags
          url: /tags
          weight: 5
        # - identifier: about
        #   name: About
        #   url: /about
        #   weight: 4


# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
    highlight:
        # anchorLineNos: true
        codeFences: true
        guessSyntax: true
        lineNos: false
        style: monokai
        # hl_Lines: ''
        # lineNoStart: 1
        # lineNumbersInTable: true
        # noClasses: true
        # tabWidth: 4
